# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.vm.box_version = "4.3.12"

  # Network configuration
  # Uncomment to enable private network:
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Uncomment to enable port forwarding:
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Synced folders

  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "/home/mrtaveras/pjt/project-2025/DevOps/Vagrant/ScriptsFolder", "/vagrantScriptsFolder"

  # Provider configuration
  config.vm.provider "libvirt" do |provider|
    provider.memory = 1024
    provider.cpus = 2
  end

  # Provisioning

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
#     apt-get install -y apache2
  SHELL
end
