# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # VM Configuration
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  # Network Configuration
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Shared Folders --> only sync changes from host to guest
  # if you want bidirectional sync, use virtiofs type instead of rsync, but requires libvirt 6.0+ and | memorybacking :shared | and the OS supports it

  config.vm.synced_folder "/home/mrtaveras/pjt/project-2025/DevOps/Vagrant/ScriptsFolder", "/vagrantScriptsFolder"

  # Provider Configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 2
  end

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    # bash /vagrantScriptsFolder/OSDeepInf.sh
  SHELL
end
